from django.urls import path
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView
from . import views
from . import help_views
from . import ticket_views
from . import collaboration_views
from . import content_image_views

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='dashboard', permanent=False), name='home'),
    path('verify/', views.verify_email, name='verify_email'),
    path('dashboard/', views.HomeDashboardView.as_view(), name='dashboard'),
    path(
        'dashboard/teacher-live-attention/',
        views.teacher_live_attention_ajax,
        name='teacher_live_attention',
    ),
    # path('login/', auth_views.LoginView.as_view(
    #     template_name='assessment_tool/login.html',
    #     redirect_authenticated_user=True),
    #     name='login'),
    path('login/', views.login_view, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path(
        'reset-password/<str:code>/',
        views.password_reset_confirm_view,
        name='password_reset_confirm',
    ),
    path('qa/', help_views.help_view, name='qa'),
    path('qa/api/search/', help_views.help_search_api, name='qa_search_api'),
    path('qa/admin/', help_views.help_admin_view, name='qa_admin'),
    path(
        'qa/admin/api/search/',
        help_views.help_admin_search_api,
        name='qa_admin_search_api',
    ),
    path(
        'qa/admin/<int:article_id>/edit/',
        help_views.help_admin_edit_view,
        name='qa_admin_edit',
    ),
    path('qa/<int:article_id>/', help_views.help_detail_view, name='qa_detail'),
    path('contact-us/', ticket_views.contact_us_view, name='contact_us'),
    path('tickets/', ticket_views.tickets_admin_view, name='tickets_admin'),
    path('tickets/new/', ticket_views.ticket_create_view, name='ticket_create'),
    path(
        'tickets/contact/<int:contact_id>/convert/',
        ticket_views.contact_convert_view,
        name='contact_convert',
    ),
    path(
        'tickets/contact/<int:contact_id>/delete/',
        ticket_views.contact_delete_view,
        name='contact_delete',
    ),
    path(
        'tickets/api/qa-search/',
        ticket_views.ticket_qa_search_api,
        name='ticket_qa_search_api',
    ),
    path(
        'tickets/t/<str:access_token>/',
        ticket_views.ticket_client_view,
        name='ticket_client',
    ),
    path(
        'tickets/<int:ticket_id>/',
        ticket_views.ticket_admin_detail_view,
        name='ticket_admin_detail',
    ),
    path('notifications/', views.notifications_view, name='notifications'),
    path(
        'notifications/load-more/',
        views.notifications_load_more_ajax,
        name='notifications_load_more',
    ),
    path('notifications/<int:notification_id>/', views.notification_detail_view, name='notification_detail'),
    path('notifications/<int:notification_id>/delete/', views.notification_delete_view, name='notification_delete'),
    path('notifications/<int:notification_id>/restore/', views.notification_restore_view, name='notification_restore'),
    path('account/', views.account_settings_view, name='account_settings'),
    path(
        'parent/grade-summary/<int:student_id>/<int:course_id>/',
        views.parent_grade_summary_view,
        name='grade_summary',
    ),
    path('register/', views.register_teacher, name='register'),
    path('db-viewer/', views.database_viewer, name='db_viewer'),
    path('courses/', views.course_list_view, name='course_list'),
    # 1. The main file explorer page
    path('explorer/', views.file_explorer, name='file_explorer'),
    # 2. AJAX endpoint to get contents for a folder column
    path('get-folder-contents/<int:group_id>/', views.get_folder_contents, name='get_folder_contents'),
    # 3. AJAX endpoint to get the preview/metadata for a specific item
    path('get-item-preview/<str:item_type>/<int:item_id>/', views.get_item_preview, name='get_item_preview'),
    path('create-folder/', views.create_folder, name='create_folder'),
    path('rename-item/', views.rename_item, name='rename_item'),
    path('delete-item/', views.delete_item, name='delete_item'),
    path('delete-item/<str:item_type>/<int:item_id>/', views.delete_item, name='delete_item_with_args'),
    path('trash/restore/', views.restore_trash_item_view, name='restore_trash_item'),
    path('collaboration/groups/', collaboration_views.manage_groups_data, name='manage_groups_data'),
    path('collaboration/groups/create/', collaboration_views.manage_group_create, name='manage_group_create'),
    path('collaboration/groups/cleanup-empty/', collaboration_views.manage_groups_cleanup_empty, name='manage_groups_cleanup_empty'),
    path('collaboration/groups/<int:pg_id>/', collaboration_views.manage_group_detail, name='manage_group_detail'),
    path('collaboration/groups/<int:pg_id>/add/', collaboration_views.manage_group_add_member, name='manage_group_add_member'),
    path('collaboration/groups/<int:pg_id>/remove/', collaboration_views.manage_group_remove_member, name='manage_group_remove_member'),
    path('collaboration/groups/<int:pg_id>/add-subgroup/', collaboration_views.manage_group_add_subgroup, name='manage_group_add_subgroup'),
    path('collaboration/groups/<int:pg_id>/remove-subgroup/', collaboration_views.manage_group_remove_subgroup, name='manage_group_remove_subgroup'),
    path('collaboration/groups/<int:pg_id>/delete/', collaboration_views.manage_group_delete, name='manage_group_delete'),
    path('collaboration/groups/<int:pg_id>/transfer/', collaboration_views.manage_group_transfer_owner, name='manage_group_transfer_owner'),
    path('collaboration/users/search/', collaboration_views.collab_user_search, name='collab_user_search'),
    path('collaboration/share/<int:branch_id>/', collaboration_views.share_item_context, name='share_item_context'),
    path('collaboration/share/<int:branch_id>/grant/', collaboration_views.share_item_grant, name='share_item_grant'),
    path('collaboration/share/<int:branch_id>/update-perm/', collaboration_views.share_item_update_perm, name='share_item_update_perm'),
    path('collaboration/share/<int:branch_id>/revoke/', collaboration_views.share_item_revoke, name='share_item_revoke'),
    path('collaboration/share/<int:branch_id>/unshare/', collaboration_views.share_item_unshare, name='share_item_unshare'),
    path('collaboration/share/<int:branch_id>/leave/', collaboration_views.share_item_leave, name='share_item_leave'),
    path('collaboration/copy-to-workspace/', collaboration_views.copy_to_workspace, name='copy_to_workspace'),
    path('collaboration/move-item/', collaboration_views.move_item, name='move_item'),
    path('collaboration/reorder/', collaboration_views.reorder_siblings, name='reorder_siblings'),
    path('get-branch-preview/<int:branch_id>/', collaboration_views.branch_preview, name='branch_preview'),
    path('courses/<int:course_id>/', views.course_detail_view, name='course_detail'),
    path('assessments/<int:assessment_id>/edit/', views.assessment_edit_by_id_view, name='assessment_edit_by_id'),
    path('course/<int:course_id>/management/', views.course_management_view, name='course_management'),
    path(
        'course/<int:course_id>/management/teacher-lookup/',
        views.course_teacher_lookup_api,
        name='course_teacher_lookup',
    ),
    path(
        'teacher-invite/<str:code>/',
        views.teacher_invite_redeem_view,
        name='teacher_invite_redeem',
    ),
    path('invite/<str:code>/', views.course_invite_redeem_view, name='course_invite_redeem'),
    path('invite/<str:code>/signup/', views.course_invite_signup_view, name='course_invite_signup'),
    path('parent-invite/<str:code>/', views.parent_invite_redeem_view, name='parent_invite_redeem'),
    path(
        'parent-invite/<str:code>/signup/',
        views.parent_invite_signup_view,
        name='parent_invite_signup',
    ),
    path('course/<int:course_id>/assessments/', views.assessment_view, name='assessment_view'),
    path('course/<int:course_id>/assessments/create/', views.create_assessment_ajax, name='create_assessment_ajax'),
    path('course/<int:course_id>/assessments/update-status/', views.update_assessment_status_ajax, name='update_assessment_status_ajax'),
    path(
        'course/<int:course_id>/assessment/<int:assessment_id>/generation-status/',
        views.assessment_generation_status_ajax,
        name='assessment_generation_status',
    ),
    path(
        'course/<int:course_id>/assessment/<int:assessment_id>/take/',
        views.student_assessment_take_view,
        name='student_assessment_take',
    ),
    path(
        'course/<int:course_id>/assessment/<int:assessment_id>/take/start/',
        views.student_assessment_start_ajax,
        name='student_assessment_start',
    ),
    path(
        'course/<int:course_id>/assessment/<int:assessment_id>/take/autosave/',
        views.student_assessment_autosave_ajax,
        name='student_assessment_autosave',
    ),
    path(
        'course/<int:course_id>/assessment/<int:assessment_id>/take/submit/',
        views.student_assessment_submit_ajax,
        name='student_assessment_submit',
    ),
    path(
        'course/<int:course_id>/assessment/<int:assessment_id>/take/status/',
        views.student_assessment_take_status_ajax,
        name='student_assessment_take_status',
    ),
    path(
        'course/<int:course_id>/assessment/<int:assessment_id>/take/focus-lock/',
        views.student_assessment_focus_lock_ajax,
        name='student_assessment_focus_lock',
    ),
    path(
        'course/<int:course_id>/assessment/<int:assessment_id>/take/submit-locked/',
        views.student_assessment_submit_locked_ajax,
        name='student_assessment_submit_locked',
    ),
    path('course/<int:course_id>/grades/', views.course_grades_view, name='course_grades'),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/',
        views.course_grades_assessment_view,
        name='course_grades_assessment',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/performance/',
        views.course_grades_assessment_performance_view,
        name='course_grades_assessment_performance',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/manual/',
        views.course_grades_manual_batch_view,
        name='course_grades_manual_batch',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/manual/payload/',
        views.course_grades_manual_batch_payload_ajax,
        name='course_grades_manual_batch_payload',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/question/<int:slot_index>/',
        views.course_grades_question_batch_view,
        name='course_grades_question_batch',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/question/<int:slot_index>/payload/',
        views.course_grades_question_batch_payload_ajax,
        name='course_grades_question_batch_payload',
    ),
    path(
        'course/<int:course_id>/grades/aggregation/',
        views.course_grades_aggregation_ajax,
        name='course_grades_aggregation',
    ),
    path(
        'course/<int:course_id>/grades/options/',
        views.course_grades_options_ajax,
        name='course_grades_options',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/options/',
        views.course_grades_assessment_options_ajax,
        name='course_grades_assessment_options',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/weight/',
        views.course_grades_assessment_weight_ajax,
        name='course_grades_assessment_weight',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/curve/',
        views.course_grades_assessment_curve_ajax,
        name='course_grades_assessment_curve',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/release/',
        views.course_grades_assessment_release_ajax,
        name='course_grades_assessment_release',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/attempt/<int:attempt_id>/action/',
        views.course_grades_attempt_action_ajax,
        name='course_grades_attempt_action',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/attempt/<int:attempt_id>/',
        views.course_grades_attempt_view,
        name='course_grades_attempt',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/attempt/<int:attempt_id>/payload/',
        views.course_grades_attempt_payload_ajax,
        name='course_grades_attempt_payload',
    ),
    path(
        'course/<int:course_id>/grades/assessment/<int:assessment_id>/attempt/<int:attempt_id>/save/',
        views.course_grades_attempt_save_ajax,
        name='course_grades_attempt_save',
    ),
    path('courses/api/assessment/<int:assessment_id>/update-window/', views.update_assessment_window_ajax, name='update_assessment_window_ajax'),
    path('courses/api/assessment/<int:assessment_id>/trash/', views.trash_assessment_ajax, name='trash_assessment_ajax'),
    path('courses/api/course/<int:course_id>/reorder-assessments/', views.reorder_assessment_ajax, name='reorder_assessment_ajax'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/', views.assessment_setup_view, name='assessment_setup'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/practice-test/', views.assessment_practice_test_view, name='assessment_practice_test'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/practice-test/start/', views.assessment_practice_test_start_ajax, name='assessment_practice_test_start'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/practice-test/grade/', views.assessment_practice_test_grade_ajax, name='assessment_practice_test_grade'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/create-aqg/', views.create_aqg_ajax, name='create_aqg_ajax'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/rename-aqg/', views.rename_aqg_ajax, name='rename_aqg_ajax'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/reorder-aqg/', views.reorder_aqg_ajax, name='reorder_aqg_ajax'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/add-problem/', views.add_problem_to_aqg_ajax, name='add_problem_to_aqg_ajax'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/duplicate-problem/', views.duplicate_problem_in_aqg_ajax, name='duplicate_problem_in_aqg_ajax'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/move-problem/', views.move_problem_to_aqg_ajax, name='move_problem_to_aqg_ajax'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/move-problem-to-set/', views.move_problem_to_cqd_ajax, name='move_problem_to_cqd_ajax'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/remove-problem-from-set/', views.remove_problem_from_cqd_ajax, name='remove_problem_from_cqd_ajax'),
    path('course/<int:course_id>/assessment/<int:assessment_id>/setup/problem-set/<int:cqd_id>/problems/', views.cqd_problems_list_ajax, name='cqd_problems_list_ajax'),
    path('add-cqd-ajax/', views.add_cqd_to_aqg_ajax, name='add_cqd_ajax'),
    path('update-cqd-count-ajax/', views.update_cqd_count_ajax, name='update_cqd_count_ajax'),
    path('update-cqd-name-ajax/', views.update_cqd_name_ajax, name='update_cqd_name_ajax'),
    path('course/api/setup/reorder-nested-item/', views.reorder_nested_item_ajax, name='reorder_nested_item_ajax'),
    path('course/api/assessment/<int:assessment_id>/start-session/', views.start_student_assessment_session, name='start_assessment_session'),
    path('course/api/assessment/<int:assessment_id>/submit-evaluation/', views.submit_student_assessment_evaluation, name='submit_assessment_evaluation'),
    path('api/problem/<int:problem_id>/save-workspace/', views.save_problem_workspace, name='save_problem_workspace'),
    path('api/problem/<int:problem_id>/grade-workspace-preview/', views.grade_problem_workspace_preview, name='grade_problem_workspace_preview'),
    path(
        'api/content-images/upload/',
        content_image_views.content_image_upload_view,
        name='content_image_upload',
    ),
    path('problem/<int:problem_id>/workspace/', views.problem_workspace_editor, name='problem_workspace_editor'),
    path('assessment/api/validate-component-preview/', views.validate_component_preview, name='validate_component_preview'),
]