# Generated by Django 4.2.30 on 2026-04-23 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(db_comment='CONSTRAINT check_lowercase_username CHECK (LOWER(username) = username)', max_length=255, unique=True)),
                ('user_email', models.CharField(db_comment='CONSTRAINT check_lowercase_email CHECK (LOWER(user_email) = user_email)', max_length=255, unique=True)),
                ('password', models.CharField(db_column='user_password', max_length=255)),
                ('user_type', models.TextField()),
                ('gender', models.CharField(blank=True, db_comment="CONSTRAINT chk_Gender CHECK (LOWER(Gender) IN ('m', 'f', 'other'));", max_length=5, null=True)),
                ('user_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_credit', models.IntegerField(blank=True, db_comment='Default is null generally; application logic should set 0 when user_type is Teacher', null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('unactivated_account', models.BooleanField(blank=True, db_comment="When an account has a required email that hasn't been verified, then the account is not activated", null=True)),
                ('ban_account', models.BooleanField(blank=True, null=True)),
                ('ongoing_assessment', models.BooleanField(blank=True, db_comment='Use this as a quick check to see if the user is currently ongoing a test', null=True)),
                ('last_login', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'db_table': 'user_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.CharField(blank=True, db_comment="Will only be 'null' if it's the copied version assigned to a student for test taking", max_length=100, null=True)),
                ('points_weight', models.FloatField(blank=True, db_comment='This is used to make the assessment grade for all students be tilted', null=True)),
                ('status', models.TextField(blank=True, db_comment="closed, open, locked, retake available, submitted, active, inactive, upcoming. 'null' means it's not tied to an individual (like a template course)", null=True)),
                ('is_historic', models.BooleanField(db_comment="When 'true' this is used to determine if the assessment is a static, needs to be unchanged, assessment that a Student is specifically assigned to complete with a single static (with concrete, not variable, inputs) answer tied to the problems. When 'false' it determines the assessment has questions with multiple answers tied to the problems.")),
                ('start_time', models.DateTimeField(blank=True, db_comment="only an available option for the 'parent' assessment", null=True)),
                ('end_time', models.DateTimeField(blank=True, db_comment="only an available option for the 'parent' assessment", null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_num', models.IntegerField(db_comment='This is designed so there exists a database restriction on choosing more than 1 option of the same group', unique=True)),
                ('choice', models.IntegerField(db_comment='This is essentially the enum choice')),
                ('description', models.CharField(max_length=1023)),
                ('deprecated', models.BooleanField()),
            ],
            options={
                'db_table': 'assessment_option_group',
                'db_table_comment': "See 'database actions' for list of options. (I added the table name where I specified options.) count-up timer, count-down timer, desmos, lock_on, whiteboard, multiple_choice, synchronize_test, same_questions_for_each_student",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(db_comment='Represents the sub-option of the specified group')),
            ],
            options={
                'db_table': 'assessment_options',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'assessment_question_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BranchGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, unique=True)),
                ('order', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'branch_group',
                'db_table_comment': "This is essentially the same thing as a virtual 'folder'.",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('contact_purpose', models.TextField()),
                ('respond_to_email', models.CharField(max_length=255)),
                ('first_name', models.CharField(db_comment='So the response knows who to address', max_length=255)),
                ('inquiry', models.TextField()),
            ],
            options={
                'db_table': 'contact_us',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField(blank=True, null=True)),
                ('status', models.TextField()),
                ('short_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=100, null=True)),
                ('introduction', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseDefaultAssessmentOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.IntegerField(db_comment='Represents the sub-section of the specified option group')),
                ('default_setting', models.BooleanField()),
            ],
            options={
                'db_table': 'course_default_assessment_options',
                'db_table_comment': "I didn't add a method to allow only a single student to view historic, this setting is for the whole class of students that can be toggled on and off.",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CqdPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cqd_pair',
                'db_table_comment': "Identifies the list of rows by ID that the cqd table is using.\nNote: It's possible to have a circular loop if for some reason the aqg_id identifies a folder at a higher level than the cqd, perhaps put a restriction somewhere that only allows sub folders/problems to get added. (This could be a database restriction using 'constraint', but it sounds complicated and I think I'd rather program it in the javascript).. just be aware it's a problem",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomQuestionDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_count', models.IntegerField()),
            ],
            options={
                'db_table': 'custom_question_distribution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmailAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_email', models.CharField(db_comment='CONSTRAINT check_lowercase_email CHECK (LOWER(temp_email) = temp_email)', max_length=255, unique=True)),
                ('code', models.CharField(db_comment='This gets generated per user when email is changed originally. User is emailed, and needs to return the code for verification', max_length=255)),
                ('timeout', models.DateTimeField()),
            ],
            options={
                'db_table': 'email_authentication',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntitySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_answer', models.BooleanField(db_comment='When true, this will make this student interactable answer type shown by default when solving the problem')),
                ('points', models.FloatField(blank=True, null=True)),
                ('content', models.TextField()),
                ('is_answer_to_multi_choice', models.BooleanField(blank=True, db_comment="This marks the child (self) entity as a correct answer choice or not. When 'null', it means the entity is not a 'choice' option (multiple choice/checkbox/radio/dropdown/custom/etc). Should add a constraint to make sure the parent_entity.problem_type_id_originator.name is one of the allowed options if this is null.", null=True)),
                ('space_allocation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entity_segment',
                'db_table_comment': "I no longer need a 'entity_num' or 'entity_tag_list' field to track the entity string tag. I am keeping this info in the 'content' json under 'entity_name_list'",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('format_pattern', models.TextField(db_comment="This will be an html section with the <<childEntity>> inside the string in various places. There will also be a <<addOptionButton>> if applicable, which will add the 'insert_entity_pattern' into the designated <<patternInsert>> location. I used <<element>> as an example, but the json actually stores a json array list")),
                ('insert_entity_pattern', models.TextField(db_comment="Uses exact strings existing in the 'problem_type' name columns. If I don't use exact names, it won't work right.")),
                ('entity_name_list', models.TextField()),
            ],
            options={
                'db_table': 'entity_type',
                'db_table_comment': "This table will be populated with all of the variations of problem categories that a problem can have a student provide an answer for. Examples include: problem, number, string, formula, paragraph_block, radio_selection, checkbox_selection, dropdown_selection, matrix, unordered_list, etc. Also includes: 'formula_prompt', 'number_prompt', 'paragraph_prompt', 'string_prompt'",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntityUserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_score', models.FloatField(blank=True, db_comment="Score can be initially set to 'null' if it requires Teacher to do the grading.", null=True)),
                ('content', models.TextField(blank=True, db_comment='Depending on the entity_type that is tied to the entity_segment, how the json is read as information will change. It is a good idea to consistently organize all data as a json though. This could be a string, an image (canvas/graph), a series of data representing a canvas/graph, a number/float, a formula, etc', null=True)),
            ],
            options={
                'db_table': 'entity_user_input',
                'db_table_comment': 'The json will identify the difference between a student answer to the question, a calculated answer, or just an entity calculation that sets up the problem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FinalGradeCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('assessment_grade_points', models.FloatField(blank=True, db_comment='This identifies the numeric score of a given assessment for the student', null=True)),
                ('assessment_grade_max_points', models.FloatField(blank=True, db_comment='This identifies the maximum possible score of a given assessment for a student', null=True)),
            ],
            options={
                'db_table': 'final_grade_calculation',
                'db_table_comment': 'I primarily intend this table to be used as a source of obtaining the grades after the course has been closed. The assessment and course can be deleted, but the grades will remain.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('status', models.TextField()),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('currency', models.CharField(max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LoginLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_entry', models.TextField()),
                ('state', models.BooleanField(blank=True, db_comment="For login attempts, this will be marked 'true' for successful login or 'false' for unsuccessful login attempts", null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('entry_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'login_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('send_on', models.DateTimeField(blank=True, null=True)),
                ('expr_date', models.DateTimeField(blank=True, db_comment='If there is a system update for instance, no need to still bring this notification to attention after the update has been scheduled to be completed.', null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PermissionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permission_group',
                'db_table_comment': 'Simply creates virtual groups that a set of permissions can apply to. For instance, to mass enable certain folder access by adding a user to the permission group.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_status', models.TextField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'problem',
                'db_table_comment': 'It is possible for both aqg_id and cqd_id to be null or not null at the same time since they can fulfill both roles simultaneously',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'problem_tags',
                'db_table_comment': "List (perhaps large list) of tag names associated with a problem that can be used later to filter problems. This could be anything from 'generated problem' to 'points above 5' to 'matrix'/'multiple choice'",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('answer', models.TextField(db_comment='The content could be anything from text to an embedded video')),
                ('user_restriction_level', models.TextField(blank=True, db_comment="This identifies which users the Q&A can be seen by. Different users have different Q&A needs. 'null' means publicly viewable.", null=True)),
                ('creation_date', models.DateTimeField()),
                ('modification_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'Q_A',
                'db_table_comment': "IT Support->Teacher->Student->Parent->public - In this order the higher tier can view lower tier Q&A.\nI mentioned in the Requirements Document that I will allow 'tags' to be assigned to the Q&A for easier lookup later. I decided now is not the time to implement this.",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(db_comment="This is the main paragraph content the question resides in. The content can hold 'answer' insert tag entities that will replace the inner data with other things later compiled.")),
                ('space_allocation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question_block',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'question_type',
                'db_table_comment': "This will be a large table of 'tags' covering all sorts of subjects. It could be as high level as 'calculus', 'trig', or other levels like 'linear', 'factoring' 'matrix', 'integral' 'derivative', etc. It will be used to filter types of math problems. (and see how many of each type of question reside inside the group)",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(db_comment='active, canceled, past_due', max_length=20)),
                ('subscription_id', models.CharField(blank=True, db_comment='e.g., sub_456', null=True, unique=True)),
                ('customer_id', models.CharField(blank=True, db_comment='e.g., cus_abc123', null=True, unique=True)),
                ('default_payment_method_id', models.CharField(blank=True, db_comment='e.g., pm_xyz789', null=True)),
                ('total_credits_purchased', models.IntegerField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_comment='When credits might renew', null=True)),
                ('auto_renew', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subscriptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTransactions',
            fields=[
                ('transaction_id', models.CharField(db_comment='Unique ID from payment provider', max_length=255, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=50)),
                ('transaction_type', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'subscription_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('contact_purpose', models.TextField()),
                ('respond_to_email', models.CharField(max_length=255)),
                ('first_name', models.CharField(db_comment='So the response knows who to address', max_length=255)),
                ('creation_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'ticket',
                'db_table_comment': "Might want to add a 'tags' field when I actually implement this",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TicketDiscussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentor_email', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket_discussion',
                'db_table_comment': 'Essentially the chat history for a given ticket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserCourseActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_email', models.CharField(db_comment='CONSTRAINT check_lowercase_email CHECK (LOWER(temp_email) = temp_email)', max_length=255, unique=True)),
                ('code', models.CharField(db_comment='This gets generated per user when email is changed originally. User is emailed, and needs to return the code for verification', max_length=255)),
                ('timeout', models.DateTimeField(db_comment='Perhaps there is no timeout here')),
            ],
            options={
                'db_table': 'user_course_activation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.TextField()),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_group',
                'db_table_comment': "This is essentially the same thing as a permission list per 'branch_group' folder",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersInCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_access', models.TextField()),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users_in_course',
                'db_table_comment': 'If a user is listed in this table, then they automatically are assigned to the course. Teachers will show up as Teachers, Students will show up as Students.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenStudentAssessmentOverwrite',
            fields=[
                ('a', models.OneToOneField(db_comment='assessment.id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='assessment_tool.assessment')),
                ('status_open', models.BooleanField(blank=True, db_comment="true means 'open', false means 'closed'", null=True)),
            ],
            options={
                'db_table': 'open_student_assessment_overwrite',
                'db_table_comment': 'There should only be a Student user id in this table. This is for when a Teacher opens an assessment for a single Student rather than the whole class.',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParentUserCourse',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parent_user_course',
                'db_table_comment': "Table used to identify that a parent can see their kid's grades for a particular course",
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProblemCategories',
            fields=[
                ('problem_tag', models.OneToOneField(db_column='problem_tag', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='assessment_tool.problemtags')),
            ],
            options={
                'db_table': 'problem_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionGroupFilters',
            fields=[
                ('assessment_question_group', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='assessment_tool.assessmentquestiongroup')),
            ],
            options={
                'db_table': 'question_group_filters',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPermissionGroup',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='assessment_tool.permissiongroup')),
                ('pg_id', models.IntegerField()),
            ],
            options={
                'db_table': 'user_permission_group',
                'db_table_comment': 'Pairs users with groups. It will show they have respective permissions the given group has.',
                'managed': False,
            },
        ),
    ]
