# Generated by Django 4.2.30 on 2026-05-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'managed': False},
        ),
    ]
