#!/usr/bin/env bash
# Export one Public Library share-root subtree from local Postgres for promote.
# Usage:
#   ./promote_public_unit.sh "Unit 1-A Tests: Polynomial and Rational Functions" /tmp/unit1a_export
set -euo pipefail

NAME="${1:?unit name required}"
OUT="${2:?output directory required}"
DB_NAME="${DB_ACTUAL_NAME:-postgres}"
DB_USER="${SECRET_DB_USER:-postgres}"

mkdir -p "$OUT"

ROOT_ID=$(psql -U "$DB_USER" -d "$DB_NAME" -Atc "
SELECT bg.id
FROM branch_group bg
JOIN users_group ug ON ug.branch_id = bg.id
JOIN permission_group pg ON pg.id = ug.permission_group
WHERE pg.name = 'public'
  AND bg.name = $(psql -U "$DB_USER" -d "$DB_NAME" -Atc "SELECT quote_literal('$NAME')")
LIMIT 1;
")

if [[ -z "$ROOT_ID" ]]; then
  echo "No public share root named: $NAME" >&2
  exit 1
fi

echo "Root branch_group id=$ROOT_ID"
echo "$ROOT_ID" > "$OUT/root_id.txt"
echo "$NAME" > "$OUT/unit_name.txt"

# Recursive descendants (including root)
psql -U "$DB_USER" -d "$DB_NAME" -Atc "
WITH RECURSIVE tree AS (
  SELECT id FROM branch_group WHERE id = $ROOT_ID
  UNION ALL
  SELECT bg.id FROM branch_group bg
  JOIN tree t ON bg.parent = t.id
)
SELECT id FROM tree ORDER BY id;
" > "$OUT/branch_ids.txt"

BRANCH_LIST=$(tr '\n' ',' < "$OUT/branch_ids.txt" | sed 's/,$//')
echo "Branch ids: $BRANCH_LIST"

# Payload ids by folder_type conventions used in this app
psql -U "$DB_USER" -d "$DB_NAME" -Atc "
SELECT a.id FROM assessment a WHERE a.id IN ($BRANCH_LIST);
" > "$OUT/assessment_ids.txt" || true
psql -U "$DB_USER" -d "$DB_NAME" -Atc "
SELECT p.id FROM problem p WHERE p.id IN ($BRANCH_LIST);
" > "$OUT/problem_ids.txt" || true
psql -U "$DB_USER" -d "$DB_NAME" -Atc "
SELECT aqg.id FROM assessment_question_group aqg WHERE aqg.id IN ($BRANCH_LIST);
" > "$OUT/aqg_ids.txt" || true
psql -U "$DB_USER" -d "$DB_NAME" -Atc "
SELECT c.id FROM custom_question_distribution c WHERE c.id IN ($BRANCH_LIST);
" > "$OUT/cqd_ids.txt" || true

# Dump selected tables filtered by ids (schema-qualified COPY via temp)
EXPORT_SQL="$OUT/export.sql"
{
  echo "BEGIN;"
  echo "-- Generated by promote_public_unit.sh for: $NAME"
} > "$EXPORT_SQL"

dump_filtered() {
  local table="$1"
  local where="$2"
  local fname="$OUT/${table}.csv"
  psql -U "$DB_USER" -d "$DB_NAME" -c "\\copy (SELECT * FROM ${table} WHERE ${where}) TO '${fname}' WITH CSV HEADER"
  if [[ -s "$fname" ]] && [[ $(wc -l < "$fname") -gt 1 ]]; then
    echo "Exported $table"
  else
    rm -f "$fname"
    echo "Skip empty $table"
  fi
}

dump_filtered branch_group "id IN ($BRANCH_LIST)"
dump_filtered users_group "branch_id = $ROOT_ID"
dump_filtered assessment "id IN ($BRANCH_LIST)"
dump_filtered assessment_question_group "id IN ($BRANCH_LIST)"
dump_filtered custom_question_distribution "id IN ($BRANCH_LIST)"
dump_filtered problem "id IN ($BRANCH_LIST)"
dump_filtered assessment_options "assessment_id IN ($BRANCH_LIST)"

PROB_LIST=$(tr '\n' ',' < "$OUT/problem_ids.txt" | sed 's/,$//')
AQG_LIST=$(tr '\n' ',' < "$OUT/aqg_ids.txt" | sed 's/,$//')
CQD_LIST=$(tr '\n' ',' < "$OUT/cqd_ids.txt" | sed 's/,$//')

if [[ -n "${PROB_LIST:-}" ]]; then
  dump_filtered question_block "problem_id IN ($PROB_LIST)"
  # entity_segment via question blocks
  QB_LIST=$(psql -U "$DB_USER" -d "$DB_NAME" -Atc "SELECT id FROM question_block WHERE problem_id IN ($PROB_LIST)" | tr '\n' ',' | sed 's/,$//')
  if [[ -n "$QB_LIST" ]]; then
    dump_filtered entity_segment "question_block_id IN ($QB_LIST)"
  fi
fi
if [[ -n "${CQD_LIST:-}" ]]; then
  dump_filtered cqd_pair "cqd_id IN ($CQD_LIST)"
fi
if [[ -n "${AQG_LIST:-}" && -n "${PROB_LIST:-}" ]]; then
  dump_filtered problem_categories "problem_id IN ($PROB_LIST)" || true
fi

# content_image: any storage_path mentioned in exported question_block HTML
if [[ -f "$OUT/question_block.csv" ]]; then
  psql -U "$DB_USER" -d "$DB_NAME" -Atc "
    SELECT DISTINCT ci.id
    FROM content_image ci
    JOIN question_block qb ON qb.content ILIKE '%' || ci.storage_path || '%'
    WHERE qb.problem_id IN (${PROB_LIST:-0});
  " > "$OUT/content_image_ids.txt" || true
  CI_LIST=$(tr '\n' ',' < "$OUT/content_image_ids.txt" | sed 's/,$//')
  if [[ -n "${CI_LIST:-}" ]]; then
    dump_filtered content_image "id IN ($CI_LIST)"
  fi
fi

echo "Export CSVs written under $OUT"
echo "Import on live after schema + admins: use promote_public_unit_import.sh"
