"""
Django settings for math_assessment_platform project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure-79=f)8y(0s0&g=qy#++j^sxaycjw%nzx5gy$)fug96w^gc90j*',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Local + temporary public tunnels (cloudflared trycloudflare / ngrok).
# Override with ALLOWED_HOSTS=host1,host2 in .env if needed.
ALLOWED_HOSTS = [
    h.strip()
    for h in config(
        'ALLOWED_HOSTS',
        default='localhost,127.0.0.1,.trycloudflare.com,.ngrok-free.app,.ngrok.io',
    ).split(',')
    if h.strip()
]

# HTTPS tunnels terminate TLS externally; tell Django the original scheme.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Required for login/forms through temporary https://*.trycloudflare.com (etc.) links.
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in config(
        'CSRF_TRUSTED_ORIGINS',
        default=(
            'https://*.trycloudflare.com,'
            'https://*.ngrok-free.app,'
            'https://*.ngrok.io'
        ),
    ).split(',')
    if o.strip()
]


# Application definition

INSTALLED_APPS = [
    'assessment_tool',
    'imagekit',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'assessment_tool.middleware.OneSessionPerUserMiddleware', # must come after 'AuthenticationMiddleware' and 'MessageMiddleware'
    'assessment_tool.middleware.ActiveAssessmentRedirectMiddleware',
    'assessment_tool.middleware.ContentViewOnlyMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'math_assessment_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'assessment_tool.context_processors.notifications',
                'assessment_tool.context_processors.content_view_only',
            ],
        },
    },
]

WSGI_APPLICATION = 'math_assessment_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'OPTIONS': {
            'target_session_attrs': 'read-write',
        },
        'NAME': config('DB_ACTUAL_NAME'),
        'USER': config('SECRET_DB_USER'),
        'PASSWORD': config('DB_USER_PASSWORD'),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Overwrite the django 'User' table to use my database 'UserProfile' table:
AUTH_USER_MODEL = 'assessment_tool.UserProfile'


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Make it so the login process allows either the email or username for login:
AUTHENTICATION_BACKENDS = [
    'assessment_tool.backends.UsernameOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend', # Keep this as a fallback
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# I need to run this before tests are initially run to swap all the models 
#  to managed=True so it can make temporary dummy databases
TEST_RUNNER = 'test_runner.ManagedModelTestRunner'

# settings.py
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'login'
LOGIN_URL = 'login'

# The absolute filesystem path to the directory that will hold user-uploaded files.
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# URL that handles the media served from MEDIA_ROOT.
MEDIA_URL = '/media/'

# Auth-gated uploads (credit invoices, etc.). Never served via MEDIA_URL.
PRIVATE_FILE_ROOT = os.path.join(BASE_DIR, 'private_files')

# Allow credit invoice PDFs up to ~25 MB (stored as-is, not resized).
DATA_UPLOAD_MAX_MEMORY_SIZE = 26 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

# Outbound email (SMTP). Credentials live in the repo-root .env.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('OUTGOING_SERVER_HOST')
EMAIL_PORT = config('OUTGOING_SERVER_PORT_SMTP', cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=config('EMAIL_HOST_USER'))
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Used to build absolute links in emails when no HTTP request is available.
PUBLIC_BASE_URL = config('PUBLIC_BASE_URL', default='http://127.0.0.1:8000').rstrip('/')
