-- Content images for Quill/workspace HTML (append-only files under media/content_images/).
-- Safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS content_image (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  storage_path character varying(512) NOT NULL,
  original_filename character varying(255),
  content_type character varying(64),
  byte_size integer,
  uploaded_by_id integer REFERENCES user_profile(user_id) ON DELETE SET NULL DEFERRABLE,
  creation_date timestamp without time zone DEFAULT now() NOT NULL,
  maybe_unused_at timestamp without time zone,
  CONSTRAINT uq_content_image_storage_path UNIQUE (storage_path)
);

CREATE INDEX IF NOT EXISTS idx_content_image_maybe_unused
  ON content_image (maybe_unused_at)
  WHERE maybe_unused_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_content_image_uploaded_by
  ON content_image (uploaded_by_id);

COMMENT ON TABLE content_image IS
  'Registry of optimized Quill/content images stored under MEDIA content_images/. Append-only; GC deletes unused rows.';

COMMENT ON COLUMN content_image.maybe_unused_at IS
  'Set when a referring HTML save dropped this image URL; daily GC verifies with a full scan before delete.';

COMMIT;
