-- Teacher seat-credit system: profile counters, ledger, purchase stub.
-- Safe to re-run.

BEGIN;

ALTER TABLE user_profile
  ADD COLUMN IF NOT EXISTS lifetime_credits_acquired integer NOT NULL DEFAULT 0;

ALTER TABLE user_profile
  ADD COLUMN IF NOT EXISTS lifetime_seat_debits integer NOT NULL DEFAULT 0;

ALTER TABLE user_profile
  ADD COLUMN IF NOT EXISTS lifetime_seat_reimbursements integer NOT NULL DEFAULT 0;

ALTER TABLE user_profile
  ADD COLUMN IF NOT EXISTS teacher_unlocked boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN user_profile.lifetime_credits_acquired IS
  'Total credits ever acquired (purchase, admin grant, transfer-in).';
COMMENT ON COLUMN user_profile.lifetime_seat_debits IS
  'Total seat credits spent on student invites.';
COMMENT ON COLUMN user_profile.lifetime_seat_reimbursements IS
  'Total seat credits returned via void/revoke/kick reimbursement.';
COMMENT ON COLUMN user_profile.teacher_unlocked IS
  'Cached: balance >= 1 OR (lifetime_seat_debits - lifetime_seat_reimbursements) > 0. Recomputed on ledger mutations.';

CREATE TABLE IF NOT EXISTS credit_purchase (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES user_profile(user_id) ON DELETE CASCADE DEFERRABLE,
  pack_size integer NOT NULL,
  list_unit_price numeric(10, 2) NOT NULL,
  unit_price numeric(10, 2) NOT NULL,
  discount_percent numeric(5, 2) NOT NULL DEFAULT 0,
  total_amount numeric(10, 2) NOT NULL,
  status character varying(32) NOT NULL DEFAULT 'pending',
  provider character varying(64) NOT NULL DEFAULT 'stub',
  provider_ref character varying(255),
  note text,
  creation_date timestamp without time zone DEFAULT now() NOT NULL,
  completed_at timestamp without time zone,
  CONSTRAINT chk_credit_purchase_status
    CHECK (status IN ('pending', 'completed', 'canceled', 'rejected')),
  CONSTRAINT chk_credit_purchase_pack_size CHECK (pack_size > 0)
);

CREATE INDEX IF NOT EXISTS idx_credit_purchase_user
  ON credit_purchase (user_id);

CREATE INDEX IF NOT EXISTS idx_credit_purchase_status
  ON credit_purchase (status);

COMMENT ON TABLE credit_purchase IS
  'Teacher credit pack purchases. Payment provider is stub until checkout is wired.';

CREATE TABLE IF NOT EXISTS credit_ledger (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL REFERENCES user_profile(user_id) ON DELETE CASCADE DEFERRABLE,
  delta integer NOT NULL,
  balance_after integer NOT NULL,
  reason character varying(64) NOT NULL,
  actor_user_id integer REFERENCES user_profile(user_id) ON DELETE SET NULL DEFERRABLE,
  related_invite_id integer,
  related_enrollment_id integer,
  related_purchase_id integer REFERENCES credit_purchase(id) ON DELETE SET NULL DEFERRABLE,
  note text,
  creation_date timestamp without time zone DEFAULT now() NOT NULL,
  CONSTRAINT chk_credit_ledger_reason CHECK (reason IN (
    'purchase',
    'admin_grant',
    'admin_revoke',
    'transfer_in',
    'transfer_out',
    'invite_spend',
    'invite_void_reimburse',
    'kick_reimburse',
    'adjustment'
  ))
);

CREATE INDEX IF NOT EXISTS idx_credit_ledger_user_created
  ON credit_ledger (user_id, creation_date DESC);

CREATE INDEX IF NOT EXISTS idx_credit_ledger_reason_created
  ON credit_ledger (reason, creation_date DESC);

CREATE UNIQUE INDEX IF NOT EXISTS uq_credit_ledger_invite_reason
  ON credit_ledger (reason, related_invite_id)
  WHERE related_invite_id IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS uq_credit_ledger_enrollment_reason
  ON credit_ledger (reason, related_enrollment_id)
  WHERE related_enrollment_id IS NOT NULL;

COMMENT ON TABLE credit_ledger IS
  'Append-only audit of teacher credit balance changes.';

-- Invoice PDF attachments: see credit_invoices.sql
-- Purchase approval / history fields: see credit_purchase_approval.sql

COMMIT;
