-- Credit invoice PDFs (private storage; served only via authenticated download).
-- Safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS credit_invoice (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id integer NOT NULL REFERENCES user_profile(user_id) ON DELETE CASCADE DEFERRABLE,
  uploaded_by_id integer REFERENCES user_profile(user_id) ON DELETE SET NULL DEFERRABLE,
  storage_path character varying(512) NOT NULL,
  original_filename character varying(255),
  content_type character varying(64) NOT NULL DEFAULT 'application/pdf',
  byte_size integer,
  creation_date timestamp without time zone DEFAULT now() NOT NULL,
  CONSTRAINT uq_credit_invoice_storage_path UNIQUE (storage_path)
);

CREATE INDEX IF NOT EXISTS idx_credit_invoice_owner
  ON credit_invoice (owner_user_id);

COMMENT ON TABLE credit_invoice IS
  'PDF invoices for credit purchases/grants. Files live under private_files/, not public media.';

ALTER TABLE credit_purchase
  ADD COLUMN IF NOT EXISTS invoice_id integer
    REFERENCES credit_invoice(id) ON DELETE SET NULL DEFERRABLE;

CREATE INDEX IF NOT EXISTS idx_credit_purchase_invoice
  ON credit_purchase (invoice_id)
  WHERE invoice_id IS NOT NULL;

ALTER TABLE credit_ledger
  ADD COLUMN IF NOT EXISTS invoice_id integer
    REFERENCES credit_invoice(id) ON DELETE SET NULL DEFERRABLE;

CREATE INDEX IF NOT EXISTS idx_credit_ledger_invoice
  ON credit_ledger (invoice_id)
  WHERE invoice_id IS NOT NULL;

COMMIT;
