-- Parent grade-access invitations (unmanaged). Safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS parent_course_invitation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer NOT NULL REFERENCES course(id) ON DELETE CASCADE DEFERRABLE,
  student_id integer NOT NULL REFERENCES user_profile(user_id) ON DELETE CASCADE DEFERRABLE,
  temp_email character varying(255) NOT NULL,
  code character varying(255) NOT NULL,
  timeout timestamp without time zone NOT NULL,
  status character varying(32) NOT NULL DEFAULT 'pending',
  target_user_id integer NULL REFERENCES user_profile(user_id) ON DELETE SET NULL DEFERRABLE,
  created_by_id integer NULL REFERENCES user_profile(user_id) ON DELETE SET NULL DEFERRABLE,
  creation_date timestamp without time zone DEFAULT now(),
  CONSTRAINT parent_course_invitation_status_check
    CHECK (status IN ('pending'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pci_code
  ON parent_course_invitation (code);

CREATE UNIQUE INDEX IF NOT EXISTS uq_pci_pending_course_student_email
  ON parent_course_invitation (course_id, student_id, lower(temp_email))
  WHERE status = 'pending';

CREATE UNIQUE INDEX IF NOT EXISTS uq_pci_pending_course_student_target
  ON parent_course_invitation (course_id, student_id, target_user_id)
  WHERE status = 'pending' AND target_user_id IS NOT NULL;

COMMENT ON TABLE parent_course_invitation IS
  'Pending Parent invites for grade access to a specific Student in a Course. Void/accept delete the row.';

COMMIT;
