-- Give parent_user_course a surrogate PK for Django ORM (composite PK unsupported on Django 4.2).
-- Safe to re-run.

BEGIN;

ALTER TABLE parent_user_course
  ADD COLUMN IF NOT EXISTS id integer;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns
    WHERE table_name = 'parent_user_course'
      AND column_name = 'id'
      AND is_identity = 'YES'
  ) THEN
    -- Backfill ids if the column was added without identity.
    IF EXISTS (
      SELECT 1 FROM parent_user_course WHERE id IS NULL
    ) THEN
      WITH numbered AS (
        SELECT ctid, ROW_NUMBER() OVER () AS rn
        FROM parent_user_course
      )
      UPDATE parent_user_course p
      SET id = n.rn
      FROM numbered n
      WHERE p.ctid = n.ctid
        AND p.id IS NULL;
    END IF;

    ALTER TABLE parent_user_course
      ALTER COLUMN id SET NOT NULL;

    -- Prefer identity column when available.
    BEGIN
      ALTER TABLE parent_user_course
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    EXCEPTION
      WHEN others THEN
        -- Fallback sequence if ADD GENERATED is unavailable on this PG build.
        CREATE SEQUENCE IF NOT EXISTS parent_user_course_id_seq;
        PERFORM setval(
          'parent_user_course_id_seq',
          GREATEST(COALESCE((SELECT MAX(id) FROM parent_user_course), 0), 1),
          true
        );
        ALTER TABLE parent_user_course
          ALTER COLUMN id SET DEFAULT nextval('parent_user_course_id_seq');
        ALTER SEQUENCE parent_user_course_id_seq OWNED BY parent_user_course.id;
    END;
  END IF;
END $$;

ALTER TABLE parent_user_course
  DROP CONSTRAINT IF EXISTS parent_user_course_pkey;

ALTER TABLE parent_user_course
  ADD CONSTRAINT parent_user_course_pkey PRIMARY KEY (id);

ALTER TABLE parent_user_course
  DROP CONSTRAINT IF EXISTS parent_user_course_student_parent_course_key;

ALTER TABLE parent_user_course
  ADD CONSTRAINT parent_user_course_student_parent_course_key
  UNIQUE (student_id, parent_id, course_id);

COMMIT;
