-- Temporary forgot-password reset links (unmanaged). Safe to re-run.
-- Links expire after 15 minutes (enforced in application code via timeout).

BEGIN;

CREATE TABLE IF NOT EXISTS password_reset_request (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  u_id integer NOT NULL REFERENCES user_profile(user_id) ON DELETE CASCADE DEFERRABLE,
  code character varying(255) NOT NULL,
  timeout timestamp without time zone NOT NULL,
  creation_date timestamp without time zone DEFAULT now(),
  requested_identifier character varying(255) NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_password_reset_request_code
  ON password_reset_request (code);

-- At most one pending reset per user.
CREATE UNIQUE INDEX IF NOT EXISTS uq_password_reset_request_user
  ON password_reset_request (u_id);

COMMENT ON TABLE password_reset_request IS
  'Pending forgot-password tokens. Deleted on successful reset, login, or replacement request.';

COMMIT;
