-- Q&A Help: view counts + tags (unmanaged). Safe to re-run.

BEGIN;

ALTER TABLE "Q_A"
  ADD COLUMN IF NOT EXISTS view_count integer NOT NULL DEFAULT 0;

COMMENT ON COLUMN "Q_A".view_count IS
  'Number of successful public detail-page views for this article.';

CREATE TABLE IF NOT EXISTS qa_tag (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying(64) NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_qa_tag_lower_name
  ON qa_tag (lower(name));

COMMENT ON TABLE qa_tag IS
  'Reusable Help/Q&A article tags (separate from problem_tags).';

CREATE TABLE IF NOT EXISTS qa_tag_assignment (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  qa_id integer NOT NULL REFERENCES "Q_A"(id) ON DELETE CASCADE DEFERRABLE,
  tag_id integer NOT NULL REFERENCES qa_tag(id) ON DELETE CASCADE DEFERRABLE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_qa_tag_assignment_pair
  ON qa_tag_assignment (qa_id, tag_id);

CREATE INDEX IF NOT EXISTS idx_qa_tag_assignment_tag
  ON qa_tag_assignment (tag_id);

COMMENT ON TABLE qa_tag_assignment IS
  'Many-to-many link between Q_A articles and qa_tag labels.';

COMMIT;
