-- Site-wide announcement banners (IT-scheduled). Safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS site_announcement (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title character varying(255) NOT NULL,
  message text NOT NULL,
  is_enabled boolean NOT NULL DEFAULT true,
  is_high_priority boolean NOT NULL DEFAULT false,
  starts_at timestamp without time zone,
  ends_at timestamp without time zone,
  warning_enabled boolean NOT NULL DEFAULT false,
  warning_message text,
  warning_starts_at timestamp without time zone,
  show_on_landing boolean NOT NULL DEFAULT false,
  show_on_about boolean NOT NULL DEFAULT false,
  show_on_login boolean NOT NULL DEFAULT false,
  show_on_contact_us boolean NOT NULL DEFAULT false,
  show_on_dashboard boolean NOT NULL DEFAULT false,
  show_on_login_once boolean NOT NULL DEFAULT false,
  created_by_id integer REFERENCES user_profile(user_id) ON DELETE SET NULL DEFERRABLE,
  creation_date timestamp without time zone DEFAULT now() NOT NULL,
  modification_date timestamp without time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_site_announcement_enabled
  ON site_announcement (is_enabled);

CREATE INDEX IF NOT EXISTS idx_site_announcement_schedule
  ON site_announcement (starts_at, ends_at)
  WHERE is_enabled;

COMMENT ON TABLE site_announcement IS
  'IT-managed site banners and optional post-login warnings. Page flags select surfaces; null schedule means always-on while enabled.';

-- Seed: Under Construction banner on the landing page (always on, high priority).
INSERT INTO site_announcement (
  title,
  message,
  is_enabled,
  is_high_priority,
  show_on_landing,
  creation_date,
  modification_date
)
SELECT
  'Under Construction',
  'Under Construction',
  true,
  true,
  true,
  now(),
  now()
WHERE NOT EXISTS (
  SELECT 1 FROM site_announcement
  WHERE title = 'Under Construction' AND show_on_landing = true
);

-- Production app role (no-op when the role does not exist, e.g. local postgres).
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'map_app') THEN
    EXECUTE 'ALTER TABLE site_announcement OWNER TO map_app';
    EXECUTE 'GRANT ALL ON TABLE site_announcement TO map_app';
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'editor_user') THEN
      EXECUTE 'GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE site_announcement TO editor_user';
    END IF;
    IF pg_get_serial_sequence('site_announcement', 'id') IS NOT NULL THEN
      EXECUTE format(
        'ALTER SEQUENCE %s OWNER TO map_app',
        pg_get_serial_sequence('site_announcement', 'id')
      );
      EXECUTE format(
        'GRANT ALL ON SEQUENCE %s TO map_app',
        pg_get_serial_sequence('site_announcement', 'id')
      );
    END IF;
  END IF;
END $$;

COMMIT;
