-- Student live assessment attempts (frozen, self-contained; no entity_segment FKs).
-- Applied manually (unmanaged Django tables). Safe to re-run where noted.

BEGIN;

-- Drop unused legacy answer table (replaced by student_assessment_*).
DROP TABLE IF EXISTS entity_user_input CASCADE;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'assessment_generation_job_status') THEN
    CREATE TYPE assessment_generation_job_status AS ENUM (
      'pending', 'running', 'complete', 'failed'
    );
  END IF;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'student_assessment_attempt_status') THEN
    CREATE TYPE student_assessment_attempt_status AS ENUM (
      'ready', 'in_progress', 'submitted'
    );
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS assessment_generation_job (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  assessment_id integer NOT NULL,
  status assessment_generation_job_status NOT NULL DEFAULT 'pending',
  started_at timestamp without time zone NOT NULL DEFAULT now(),
  finished_at timestamp without time zone NULL,
  error_message text NULL,
  total_students integer NOT NULL DEFAULT 0,
  completed_students integer NOT NULL DEFAULT 0,
  CONSTRAINT assessment_generation_job_assessment_id_fkey
    FOREIGN KEY (assessment_id) REFERENCES assessment(id)
    ON DELETE CASCADE DEFERRABLE
);

CREATE INDEX IF NOT EXISTS idx_assessment_generation_job_assessment
  ON assessment_generation_job (assessment_id, started_at DESC);

COMMENT ON TABLE assessment_generation_job IS
  'Tracks async per-student attempt generation when a teacher opens an assessment.';

CREATE TABLE IF NOT EXISTS student_assessment_attempt (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  enrollment_id integer NOT NULL,
  assessment_id integer NULL,
  course_id integer NOT NULL,
  status student_assessment_attempt_status NOT NULL DEFAULT 'ready',
  started_at timestamp without time zone NULL,
  submitted_at timestamp without time zone NULL,
  auto_graded_at timestamp without time zone NULL,
  earned_points double precision NULL,
  max_points double precision NULL,
  branch_id integer NULL,
  creation_date timestamp without time zone NOT NULL DEFAULT now(),
  CONSTRAINT student_assessment_attempt_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id)
    ON DELETE CASCADE DEFERRABLE,
  CONSTRAINT student_assessment_attempt_enrollment_id_fkey
    FOREIGN KEY (enrollment_id) REFERENCES student_course_enrollment(id)
    ON DELETE CASCADE DEFERRABLE,
  CONSTRAINT student_assessment_attempt_assessment_id_fkey
    FOREIGN KEY (assessment_id) REFERENCES assessment(id)
    ON DELETE SET NULL DEFERRABLE,
  CONSTRAINT student_assessment_attempt_course_id_fkey
    FOREIGN KEY (course_id) REFERENCES course(id)
    ON DELETE CASCADE DEFERRABLE,
  CONSTRAINT student_assessment_attempt_branch_id_fkey
    FOREIGN KEY (branch_id) REFERENCES branch_group(id)
    ON DELETE SET NULL DEFERRABLE
);

-- One attempt per enrollment + parent assessment for this slice.
CREATE UNIQUE INDEX IF NOT EXISTS uq_saa_enrollment_assessment
  ON student_assessment_attempt (enrollment_id, assessment_id)
  WHERE assessment_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_saa_user_status
  ON student_assessment_attempt (user_id, status);

COMMENT ON TABLE student_assessment_attempt IS
  'Frozen student take of a parent assessment; independent of later template edits/deletes.';

CREATE TABLE IF NOT EXISTS student_assessment_problem (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id integer NOT NULL,
  slot_index integer NOT NULL,
  section_name character varying(255) NULL,
  title character varying(255) NULL,
  source_problem_id integer NULL,
  body_html text NOT NULL DEFAULT '',
  render_payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  answer_key jsonb NOT NULL DEFAULT '{}'::jsonb,
  answer_fields jsonb NOT NULL DEFAULT '[]'::jsonb,
  earned_points double precision NULL,
  max_points double precision NULL,
  requires_manual_grading boolean NOT NULL DEFAULT false,
  branch_id integer NULL,
  CONSTRAINT student_assessment_problem_attempt_id_fkey
    FOREIGN KEY (attempt_id) REFERENCES student_assessment_attempt(id)
    ON DELETE CASCADE DEFERRABLE,
  CONSTRAINT student_assessment_problem_branch_id_fkey
    FOREIGN KEY (branch_id) REFERENCES branch_group(id)
    ON DELETE SET NULL DEFERRABLE
);

CREATE INDEX IF NOT EXISTS idx_sap_attempt_slot
  ON student_assessment_problem (attempt_id, slot_index);

CREATE INDEX IF NOT EXISTS idx_sap_source_problem
  ON student_assessment_problem (source_problem_id)
  WHERE source_problem_id IS NOT NULL;

COMMENT ON COLUMN student_assessment_problem.answer_key IS
  'Server-only frozen keys / entity context for one-shot grading. Never send to take clients.';

CREATE TABLE IF NOT EXISTS student_assessment_answer (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  problem_id integer NOT NULL,
  field_token character varying(255) NOT NULL,
  content jsonb NULL,
  points_score double precision NULL,
  auto_points_score double precision NULL,
  detail jsonb NULL,
  CONSTRAINT student_assessment_answer_problem_id_fkey
    FOREIGN KEY (problem_id) REFERENCES student_assessment_problem(id)
    ON DELETE CASCADE DEFERRABLE,
  CONSTRAINT student_assessment_answer_problem_field_uniq
    UNIQUE (problem_id, field_token)
);

COMMIT;
