-- Focus-leave lock history for live student assessment attempts.
-- Applied outside Django migrations because these models are unmanaged.

CREATE TABLE IF NOT EXISTS student_assessment_focus_lock (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  attempt_id integer NOT NULL,
  locked_at timestamp without time zone NOT NULL DEFAULT now(),
  unlocked_at timestamp without time zone NULL,
  unlocked_by_id integer NULL,
  unlock_reason varchar(32) NULL,
  CONSTRAINT student_assessment_focus_lock_attempt_id_fkey
    FOREIGN KEY (attempt_id)
    REFERENCES student_assessment_attempt(id)
    ON DELETE CASCADE DEFERRABLE,
  CONSTRAINT student_assessment_focus_lock_unlocked_by_id_fkey
    FOREIGN KEY (unlocked_by_id)
    REFERENCES user_profile(user_id)
    ON DELETE SET NULL DEFERRABLE
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_student_assessment_focus_lock_active
  ON student_assessment_focus_lock (attempt_id)
  WHERE unlocked_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_student_assessment_focus_lock_history
  ON student_assessment_focus_lock (attempt_id, locked_at);

COMMENT ON TABLE student_assessment_focus_lock IS
  'Focus-leave lock events for assessment attempts. Closed events remain as teacher-visible history.';

COMMENT ON COLUMN student_assessment_focus_lock.unlock_reason IS
  'teacher | submitted | window_ended | assessment_closed; NULL while actively locked.';
