-- Enrollment instances + link final grades to a specific stint.
-- Applied manually (unmanaged Django tables). Safe-ish to re-run where noted.

BEGIN;

-- Distinct from existing course_enrollment enum used by users_in_course.user_access.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'student_course_enrollment_status') THEN
    CREATE TYPE student_course_enrollment_status AS ENUM ('active', 'ended');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS student_course_enrollment (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id integer NOT NULL,
  course_id integer NOT NULL,
  status student_course_enrollment_status NOT NULL DEFAULT 'active',
  -- Examples: kicked, completed, course_closed
  end_reason character varying(64) NULL,
  started_at timestamp without time zone NOT NULL DEFAULT now(),
  ended_at timestamp without time zone NULL,
  -- Optional link to the live seat while active; cleared if the seat row is deleted.
  slot_id integer NULL,
  CONSTRAINT student_course_enrollment_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id)
    ON DELETE CASCADE DEFERRABLE,
  CONSTRAINT student_course_enrollment_course_id_fkey
    FOREIGN KEY (course_id) REFERENCES course(id)
    ON DELETE CASCADE DEFERRABLE,
  CONSTRAINT student_course_enrollment_slot_id_fkey
    FOREIGN KEY (slot_id) REFERENCES users_in_course(id)
    ON DELETE SET NULL DEFERRABLE,
  CONSTRAINT student_course_enrollment_status_dates_check CHECK (
    (status = 'active' AND ended_at IS NULL)
    OR (status = 'ended' AND ended_at IS NOT NULL)
  )
);

COMMENT ON TABLE student_course_enrollment IS
  'One row per student enrollment stint in a course. Survives kick/finish so grades can be scoped to that instance. users_in_course remains the current seat/slot only.';

COMMENT ON COLUMN student_course_enrollment.end_reason IS
  'Why the stint ended, e.g. kicked, completed, course_closed. Null while active.';

COMMENT ON COLUMN student_course_enrollment.slot_id IS
  'Optional FK to the current users_in_course seat while status=active.';

-- At most one active enrollment per student per course.
CREATE UNIQUE INDEX IF NOT EXISTS uq_sce_one_active_per_user_course
  ON student_course_enrollment (user_id, course_id)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_sce_course_user
  ON student_course_enrollment (course_id, user_id);

-- Tie historic/live final grades to an enrollment stint.
ALTER TABLE final_grade_calculation
  ADD COLUMN IF NOT EXISTS enrollment_id integer;

-- Enforce NOT NULL after the column exists (safe when table has no orphan rows).
ALTER TABLE final_grade_calculation
  ALTER COLUMN enrollment_id SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'final_grade_calculation_enrollment_id_fkey'
  ) THEN
    ALTER TABLE final_grade_calculation
      ADD CONSTRAINT final_grade_calculation_enrollment_id_fkey
      FOREIGN KEY (enrollment_id) REFERENCES student_course_enrollment(id)
      ON DELETE CASCADE DEFERRABLE;
  END IF;
END $$;

-- One grade row per assessment within an enrollment (allows multiple NULL assessment_id).
CREATE UNIQUE INDEX IF NOT EXISTS uq_fgc_enrollment_assessment
  ON final_grade_calculation (enrollment_id, assessment_id)
  WHERE assessment_id IS NOT NULL;

COMMENT ON COLUMN final_grade_calculation.enrollment_id IS
  'Student course enrollment stint this grade belongs to. Separates prior vs re-enrollment history.';

COMMIT;
