-- Co-teacher invitations (unmanaged). Safe to re-run.
-- Pending invite = row exists. Accept creates users_in_course and deletes this row.
-- Reject / void / leave also delete the invite row.

BEGIN;

CREATE TABLE IF NOT EXISTS teacher_course_invitation (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id integer NOT NULL REFERENCES course(id) ON DELETE CASCADE DEFERRABLE,
  invitee_id integer NOT NULL REFERENCES user_profile(user_id) ON DELETE CASCADE DEFERRABLE,
  invited_by_id integer NOT NULL REFERENCES user_profile(user_id) DEFERRABLE,
  code character varying(255) NOT NULL,
  creation_date timestamp without time zone DEFAULT now(),
  timeout timestamp without time zone NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_teacher_course_invitation_code
  ON teacher_course_invitation (code);

CREATE UNIQUE INDEX IF NOT EXISTS uq_teacher_course_invitation_course_invitee
  ON teacher_course_invitation (course_id, invitee_id);

CREATE INDEX IF NOT EXISTS idx_teacher_course_invitation_invitee
  ON teacher_course_invitation (invitee_id);

COMMENT ON TABLE teacher_course_invitation IS
  'Pending co-Teacher invites for a course. Deleted on accept, reject, void, or expiry cleanup.';

COMMIT;
