-- PDF attachments for Contact Us submissions and support tickets.
-- Private storage under private_files/ (not public MEDIA). Safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS contact_us_attachment (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_us_id integer NOT NULL REFERENCES contact_us(id) ON DELETE CASCADE DEFERRABLE,
  storage_path character varying(512) NOT NULL,
  original_filename character varying(255),
  content_type character varying(64) NOT NULL DEFAULT 'application/pdf',
  byte_size integer,
  creation_date timestamp without time zone DEFAULT now() NOT NULL,
  CONSTRAINT uq_contact_us_attachment_storage_path UNIQUE (storage_path)
);

CREATE INDEX IF NOT EXISTS idx_contact_us_attachment_contact
  ON contact_us_attachment (contact_us_id);

COMMENT ON TABLE contact_us_attachment IS
  'Optional PDF attached to a Contact Us submission before it is converted to a ticket.';

CREATE TABLE IF NOT EXISTS ticket_attachment (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id integer NOT NULL REFERENCES ticket(id) ON DELETE CASCADE DEFERRABLE,
  discussion_id integer REFERENCES ticket_discussion(id) ON DELETE SET NULL DEFERRABLE,
  storage_path character varying(512) NOT NULL,
  original_filename character varying(255),
  content_type character varying(64) NOT NULL DEFAULT 'application/pdf',
  byte_size integer,
  uploaded_by_id integer REFERENCES user_profile(user_id) ON DELETE SET NULL DEFERRABLE,
  creation_date timestamp without time zone DEFAULT now() NOT NULL,
  CONSTRAINT uq_ticket_attachment_storage_path UNIQUE (storage_path)
);

CREATE INDEX IF NOT EXISTS idx_ticket_attachment_ticket
  ON ticket_attachment (ticket_id);

CREATE INDEX IF NOT EXISTS idx_ticket_attachment_discussion
  ON ticket_attachment (discussion_id)
  WHERE discussion_id IS NOT NULL;

COMMENT ON TABLE ticket_attachment IS
  'PDF attachments on tickets / discussion replies. Files live under private_files/.';

COMMIT;
